<!DOCTYPE html>
<!--
/*
 * This file is part of the payment's API library.
 *
 * (c) Emerson Cavalcanti
 *
 * LICENSE: The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject
 * to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 * 
 * ---------------------------------------------------------------------
 * Descrição:
 * 
 * Layout para formatação de boleto na forma de fatura.
 * 
 * Os boletos no formato de fatura normalmente são usados para cobranças
 * que exigem maior detalhamento sobre o produto adquirido ou o serviço
 * prestado. O layout utilizado tem características específicas, e como
 * no boleto comum, o recibo do pagador fica acima da linha pontilhada e
 * a ficha de compensação fica logo abaixo. Porém, no recibo do pagador,
 * são informados os detalhes sobre àquela cobrança, que têm a função de
 * trazer as informações sobre o contrato firmado.
 * 
 * Quando o boleto é pago, o recibo fica em posse do pagador para que
 * ele possa comprovar o pagamento e ter em mãos os detalhes sobre os
 * valores que geraram a cobrança.
 */

/**
 * @author Emerson Cavalcanti <emersoncavalcanti@gmail.com>
 */
-->
<?php extract($extraData) ?>
<?php
if (!function_exists('fmtMoney')) {
  // Cria uma função de formatação de dinheiro
  function fmtMoney($value): string
  {
    if (is_numeric($value)) {
      return number_format($value, 2, ',', '.');
    } else if (is_string($value)) {
      return $value;
    }

    return '';
  }
}
?>
<?php foreach($billetsData AS $data): ?>
<?php extract($data) ?>
<html lang="pt-BR">
  <head>
    <meta charset="UTF-8">
    <style type="text/css">
      <!-- Embed the CSS content here --> 
      <?php include $resourcePath . '/css/styles.css' ?>
    </style>
  </head>
  <body>
    <div style="width: 718px">
      <?php
        $lineCount = 0;
        $pageSize = 64;
        $smallSize = 20;
      ?>
      <?php foreach($historic as $count => $row): ?>
        <?php if( is_array($row) ): ?>
          <?php if( $lineCount == 0 ): ?>
            <!-- Exibimos o cabeçalho -->
            <?php include(__DIR__ . '/partials/Header.phtml') ?>

            <!-- Iniciamos uma nova tabela -->
            <?php include(__DIR__ . '/partials/OpenTable.phtml') ?>
            <!-- Iniciamos os cabeçalhos das colunas -->
            <?php include(__DIR__ . '/partials/TableHeader.phtml') ?>
            <?php $lineCount = 1 ?>
          <?php endif; ?>
          <?php if( $row['type'] == 'warning' ): ?>
            <?php $lineCount++; ?>
            <?php if( $lineCount > ($pageSize - 2) ): ?>
              <!-- Fechamos a tabela -->
              <?php include(__DIR__ . '/partials/CloseTable.phtml') ?>
              <!-- Quebramos a página -->
              <pagebreak>
              <?php $lineCount = 1 ?>

              <!-- Exibimos o cabeçalho -->
              <?php include(__DIR__ . '/partials/Header.phtml') ?>
            <?php endif; ?>
            <tr>
              <td colspan="8">
                &nbsp;
              </td>
            </tr>
            <?php $lineCount++; ?>
            <tr>
              <?php if( $row['color'] == 'orange' ): ?>
              <td colspan="8" class="orange bold">
              <?php elseif( $row['color'] == 'graphite' ): ?>
              <td colspan="8" class="graphite bold">
              <?php elseif( $row['color'] == 'ruby' ): ?>
              <td colspan="8" class="ruby bold">
              <?php else: ?>
              <td colspan="8" class="bold">
              <?php endif; ?>
                <?php echo $row['data']; ?>
              </td>
            </tr>
            <?php $lineCount++; ?>
          <?php endif; ?>
          <?php if( $row['type'] == 'space' ): ?>
            <?php $lineCount++; ?>
            <?php if( $lineCount > ($pageSize - 2) ): ?>
              <!-- Fechamos a tabela -->
              <?php include(__DIR__ . '/partials/CloseTable.phtml') ?>
              <!-- Quebramos a página -->
              <pagebreak>
              <?php $lineCount = 1 ?>

              <!-- Exibimos o cabeçalho -->
              <?php include(__DIR__ . '/partials/Header.phtml') ?>

              <!-- Iniciamos uma nova tabela -->
              <?php include(__DIR__ . '/partials/OpenTable.phtml') ?>
              <?php include(__DIR__ . '/partials/TableHeader.phtml') ?>
            <?php endif; ?>
            <tr>
              <td colspan="8">
                &nbsp;
              </td>
            </tr>
          <?php endif; ?>
          <?php if( $row['type'] == 'group' ): ?>
            <?php $lineCount++; ?>
            <?php if( $lineCount > ($pageSize - 3) ): ?>
              <!-- Fechamos a tabela -->
              <?php include(__DIR__ . '/partials/CloseTable.phtml') ?>
              <!-- Quebramos a página -->
              <pagebreak>
              <?php $lineCount = 1 ?>

              <!-- Exibimos o cabeçalho -->
              <?php include(__DIR__ . '/partials/Header.phtml') ?>

              <!-- Iniciamos uma nova tabela -->
              <?php include(__DIR__ . '/partials/OpenTable.phtml') ?>
              <?php include(__DIR__ . '/partials/TableHeader.phtml') ?>
            <?php else: ?>
            <tr>
              <td colspan="8">
                &nbsp;
              </td>
            </tr>
            <?php endif; ?>
            <?php $lineCount++; ?>
            <tr>
              <td colspan="8" class="bold">
                <?php echo $row['name']; ?>
              </td>
            </tr>
            <?php $lineCount++; ?>
            <?php include(__DIR__ . '/partials/TableHeader.phtml') ?>
          <?php endif; ?>
          <?php if( $row['type'] == 'cols' ): ?>
            <?php
              // Obtemos as colunas
              $cols = $row['cols'];
              $contractNumber = $row['contract'];

              // Verificamos se uma das colunas possui menos elementos
              // do que outra e balanceamento
              $leftSize  = count($cols['left']);
              $rightSize = count($cols['right']);
              if ($leftSize !== $rightSize) {
                // Precisamos balancear as colunas, então determinamos
                // em qual colunas iremos acrescentar linhas em branco
                $side = ($leftSize > $rightSize)
                  ? 'right'
                  : 'left'
                ;
                $diff = abs($leftSize - $rightSize);
                do {
                  $cols[$side][] = [
                    'plate' => '',
                    'description' => '',
                    'value' => null
                  ];
                  $diff--;
                } while ($diff > 0);
              }
              $size = count($cols['left']);
            ?>
            <?php $lineCount++; ?>
            <tr>
              <td colspan="8" class="note">
                Contrato: <?php echo $contractNumber; ?>
              </td>
            </tr>
            <?php for ($item = 0; $item < $size; $item++): ?>
              <?php $lineCount++; ?>
              <?php if( ($lineCount > ($pageSize -1) && ($item === ($size - 1))) || ($lineCount > $pageSize)): ?>
                <!-- Estamos no segundo for -->
                <!-- Fechamos a tabela -->
                <?php include(__DIR__ . '/partials/CloseTable.phtml') ?>
                <!-- Quebramos a página -->
                <pagebreak>
                <?php $lineCount = 1 ?>
                <!-- Exibimos o cabeçalho -->
                <?php include(__DIR__ . '/partials/Header.phtml') ?>

                <!-- Iniciamos uma nova tabela -->
                <?php include(__DIR__ . '/partials/OpenTable.phtml') ?>
                <?php include(__DIR__ . '/partials/TableHeader.phtml') ?>
              <?php endif; ?>
              <tr>
                <td>
                  <?php echo $cols['left'][$item]['plate']; ?>
                </td>
                <td>
                  <?php echo $cols['left'][$item]['description']; ?>
                </td>
                <td class="right">
                  <?php echo fmtMoney($cols['left'][$item]['value']); ?>
                </td>
                <td width="5"></td>
                <td width="5" class="separator"></td>
                <td>
                  <?php echo $cols['right'][$item]['plate']; ?>
                </td>
                <td>
                  <?php echo $cols['right'][$item]['description']; ?>
                </td>
                <td class="right">
                  <?php echo fmtMoney($cols['right'][$item]['value']); ?>
                </td>
              </tr>
            <?php endfor; ?>
            <?php $lineCount++; ?>
            <tr>
              <td colspan="8" class="note">
                &nbsp;✔ Total: <span class="bold"><?php echo $cols['amount']; ?></span>
              </td>
            </tr>
          <?php endif; ?>
        <?php endif; ?>
      <?php endforeach; ?>
      <?php if( $lineCount < $pageSize ): ?>
        <?php if( $lineCount > $smallSize ): ?>
          <!-- Fechamos a tabela -->
          <?php include(__DIR__ . '/partials/CloseTable.phtml') ?>
          <!-- Quebramos a página -->
          <pagebreak>
          <!-- Incluímos novamente o cabeçalho -->
          <?php include(__DIR__ . '/partials/Header.phtml') ?>

          <!-- Acrescentamos espaços em branco até a altura necessária -->
          <?php
            for ($i=0; $i < $smallSize; $i++) { 
              echo "<br>";
            }
          ?>
        <?php else: ?>
          <?php while ($lineCount < $smallSize): ?>
            <?php $lineCount++; ?>
            <tr>
              <td colspan="8">
                &nbsp;
              </td>
            </tr>
          <?php endwhile; ?>
          <!-- Fechamos a tabela -->
          <?php include(__DIR__ . '/partials/CloseTable.phtml') ?>
        <?php endif; ?>
      <?php endif; ?>
      <!-- Fim do histórico -->

      <table class="simpleBorder default field">
        <tbody>
          <tr>
            <td colspan="6" width="250" class="withBorder">
              <table width="100%" class="noBorder">
                <tbody>
                  <tr>
                    <td height="10px" valign="bottom" width="100%" class="label">
                      Beneficiário
                    </td>
                  </tr>

                  <tr>
                    <td height="20px" width="100%" class="content">
                      <?php echo $emitter['name']; ?>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>

            <td class="withBorder" width="130">
              <table width="100%" class="noBorder">
                <tbody>
                  <tr>
                    <td height="10px" valign="bottom" width="100%" class="label">
                      <?php echo $emitter['documentType']; ?> do Beneficiário
                    </td>
                  </tr>

                  <tr>
                    <td height="20px" width="100%" class="content">
                      <?php echo $emitter['documentNumber']; ?>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>

            <td class="withBorder lastBorder" width="130">
              <table width="100%" class="noBorder">
                <tbody>
                  <tr>
                    <td height="10px" valign="bottom" width="100%" class="label">
                      Agência/Código do Beneficiário
                    </td>
                  </tr>

                  <tr>
                    <td height="20px" width="100%" class="content right">
                      <?php echo $emitter['agencyAndAccount']; ?>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>
          </tr>

          <tr>
            <td colspan="2" class="withBorder">
              <table width="100%" class="noBorder">
                <tbody>
                  <tr>
                    <td height="10px" valign="bottom" width="100%" class="label">
                      Data do documento
                    </td>
                  </tr>

                  <tr>
                    <td height="20px" width="100%" class="content center">
                      <?php echo $dateOfDocument; ?>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>

            <td colspan="2" class="withBorder" width="100">
              <table width="100%" class="noBorder">
                <tbody>
                  <tr>
                    <td height="10px" valign="bottom" width="100%" class="label">
                      Nº documento
                    </td>
                  </tr>

                  <tr>
                    <td height="20px" width="100%" class="content">
                      <?php echo $documentNumber; ?>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>

            <td class="withBorder">
              <table width="100%" class="noBorder">
                <tbody>
                  <tr>
                    <td height="10px" valign="bottom" width="100%" class="label">
                      Espécie doc.
                    </td>
                  </tr>
                  <tr>
                    <td height="20px" width="100%" class="content center">
                      <?php echo $kindOfDocument; ?>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>
            
            <td class="withBorder">
              <table width="100%" class="noBorder">
                <tbody>
                  <tr>
                    <td height="10px" valign="bottom" width="100%" class="label">
                      Aceite
                    </td>
                  </tr>

                  <tr>
                    <td height="20px" width="100%" class="content center">
                      <?php echo $acceptance; ?>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>

            <td class="withBorder">
              <table width="100%" class="noBorder">
                <tbody>
                  <tr>
                    <td height="10px" valign="bottom" width="100%" class="label">
                      Data processamento
                    </td>
                  </tr>

                  <tr>
                    <td height="20px" width="100%" class="content center">
                      <?php echo $dateOfProcessing; ?>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>

            <td class="withBorder lastBorder" width="130">
              <table width="100%" class="noBorder">
                <tbody>
                  <tr>
                    <td height="10px" valign="bottom" width="100%" class="label">
                      Nosso número
                    </td>
                  </tr>

                  <tr>
                    <td height="20px" width="100%" class="content right">
                      <?php echo $bankIdentificationNumber; ?>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>
          </tr>

          <tr>
            <?php if (isset($hideForBankUse)?($hideForBankUse===false):true) : ?>
            <td<?php if (isset($showCIP)?($showCIP===false):true) : ?> colspan="2"<?php endif ?> class="withBorder">
              <table width="100%" class="noBorder">
                <tbody>
                  <tr>
                    <td height="10px" valign="bottom" width="100%" class="label">
                      Uso do banco
                    </td>
                  </tr>

                  <tr>
                    <td height="20px" width="100%" class="content">
                      <?php echo $forBankUse; ?>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>
            <?php endif; ?>

            <?php if (isset($showCIP)?$showCIP:false) : ?>
            <!-- Campo exclusivo do Bradesco -->
            <td class="withBorder" width="20">
              <table width="100%" class="noBorder">
                <tbody>
                  <tr>
                    <td height="10px" valign="bottom" width="100%" class="label">
                      CIP
                    </td>
                  </tr>

                  <tr>
                    <td height="20px" width="100%" class="content">
                      <?php echo (intval($CIP) > 0)?$CIP:''; ?>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>
            <?php endif ?>
            
            <td<?php if (isset($hideForBankUse)?($hideForBankUse===true):false) : ?> colspan="3"<?php endif; ?> class="withBorder">
              <table width="100%" class="noBorder">
                <tbody>
                  <tr>
                    <td height="10px" valign="bottom" width="100%" class="label">
                      Carteira
                    </td>
                  </tr>

                  <tr>
                    <td height="20px" width="100%" class="content">
                      <?php echo $walletName; ?>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>

            <td class="withBorder" width="35">
              <table width="100%" class="noBorder">
                <tbody>
                  <tr>
                    <td height="10px" valign="bottom" width="100%" class="label">
                      Espécie
                    </td>
                  </tr>

                  <tr>
                    <td height="20px" width="100%" class="content">
                      <?php echo $specie['symbol']; ?>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>

            <td colspan="2" class="withBorder">
              <table width="100%" class="noBorder">
                <tbody>
                  <tr>
                    <td height="10px" valign="bottom" width="100%" class="label">
                      Quantidade
                    </td>
                  </tr>

                  <tr>
                    <td height="20px" width="100%" class="content center">
                      <?php echo $amount; ?>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>

            <td class="withBorder">
              <table width="100%" class="noBorder">
                <tbody>
                  <tr>
                    <td height="10px" valign="bottom" width="100%" class="label">
                      (X) Valor
                    </td>
                  </tr>

                  <tr>
                    <td height="20px" width="100%" class="content right">
                      &nbsp;
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>

            <td class="withBorder lastBorder">
              <table width="100%" class="noBorder">
                <tbody>
                  <tr>
                    <td height="10px" valign="bottom" width="100%" class="label">
                      (=) Valor Documento
                    </td>
                  </tr>

                  <tr>
                    <td height="20px" width="100%" class="content right">
                      <?php echo $documentValue; ?>
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>
          </tr>

          <tr>
            <td colspan="2" class="withBorder" width="120">
              <table width="100%" class="noBorder">
                <tbody>
                  <tr>
                    <td height="10px" valign="bottom" width="100%" class="label">
                      (-) Descontos / Abatimentos
                    </td>
                  </tr>

                  <tr>
                    <td height="20px" width="100%" class="content right">
                      &nbsp;
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>

            <td colspan="2" class="withBorder">
              <table width="100%" class="noBorder">
                <tbody>
                  <tr>
                    <td height="10px" valign="bottom" width="100%" class="label">
                      (-) Outras deduções
                    </td>
                  </tr>

                  <tr>
                    <td height="20px" width="100%" class="content right">
                      &nbsp;
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>

            <td colspan="2" class="withBorder">
              <table width="100%" class="noBorder">
                <tbody>
                  <tr>
                    <td height="10px" valign="bottom" width="100%" class="label">
                      (+) Mora / Multa
                    </td>
                  </tr>

                  <tr>
                    <td height="20px" width="100%" class="content right">
                      &nbsp;
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>

            <td class="withBorder">
              <table width="100%" class="noBorder">
                <tbody>
                  <tr>
                    <td height="10px" valign="bottom" width="100%" class="label">
                      (+) Outros acréscimos
                    </td>
                  </tr>

                  <tr>
                    <td height="20px" width="100%" class="content right">
                      &nbsp;
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>

            <td class="withBorder lastBorder">
              <table width="100%" class="noBorder">
                <tbody>
                  <tr>
                    <td height="10px" valign="bottom" width="100%" class="label">
                      (=) Valor cobrado
                    </td>
                  </tr>

                  <tr>
                    <td height="20px" width="100%" class="content right">
                      &nbsp;
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>
          </tr>

          <tr>
            <td colspan="6" class="simpleBorderTop">
              <table width="100%">
                <tbody>
                  <tr rowspan="2">
                    <td height="30px" valign="bottom" width="100%" class="header">
                      Recibo do pagador
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>

            <td colspan="2" class="simpleBorderTop">
              <table width="100%">
                <tbody>
                  <tr>
                    <td height="10px" valign="bottom" width="100%" class="label center">
                      Autenticação mecânica
                    </td>
                  </tr>

                  <tr>
                    <td height="5px" valign="bottom" width="100%" class="lightBorderLeft lightBorderTop lightBorderRight">
                    </td>
                  </tr>
                </tbody>
              </table>
            </td>
          </tr>
        </tbody>
      </table>
      <br>
      <!-- Linha de Corte -->
      <table width="100%">
        <tbody>
          <tr>
            <td height="13px" valign="bottom" class="right smallFont">
              Corte na linha pontilhada <img src="<?php echo $cutHere; ?>" width="19" height="10" border="0">
            </td>
          </tr>
          <tr>
            <td height="2px" style="border-top: 1px dotted #000000;">
              &nbsp;
            </td>
          </tr>
        </tbody>
      </table>
      
      <!-- Ficha de compensação -->
      <?php include(__DIR__ . '/partials/CompensationForm.phtml') ?>
    </div>
  </body>
</html>
<?php endforeach; ?>
