-- Cria o banco de dados
CREATE DATABASE erp;

-- Cria um usuário admin e concede os direitos
CREATE ROLE admin WITH NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN ENCRYPTED PASSWORD '#t3l3c0m#';
GRANT ALL PRIVILEGES ON DATABASE erp TO admin;
GRANT ALL PRIVILEGES ON SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO admin;

-- Cria um schema ERP
CREATE SCHEMA erp AUTHORIZATION admin;
GRANT ALL PRIVILEGES ON SCHEMA erp TO admin;

